TranslatorProject.WebUI/Controllers/TranslatorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TranslatorProject.Business.Interfaces;

namespace TranslatorProject.WebUI.Controllers
{
    [Authorize]
    public class TranslatorController : Controller
    {
        private readonly ITranslatorService _service;

        public TranslatorController
            (ITranslatorService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoadData(int pageIndex, byte langId, string wordName)
        {
            var query = _service.GetTranslatorList(pageIndex, langId, wordName);
            return Json(query);
        }
    }
}

TranslatorProject.WebUI/Controllers/WordTranslationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;
using TranslatorProject.Business.DTOs;
using TranslatorProject.Business.Interfaces;
using TranslatorProject.Common.Enums;
using TranslatorProject.Common.Models;
using TranslatorProject.WebUI.ViewModels;

namespace TranslatorProject.WebUI.Controllers
{
    [Authorize(Roles = GlobalConstants.Roles.Administrator)]
    public class WordTranslationController : Controller
    {
        private readonly IWordTranslationService _service;
        private readonly IDictionaryService _dictService;
        private readonly IMapper _mapper;

        public WordTranslationController
            (IWordTranslationService service, IDictionaryService dictService, IMapper mapper)
        {
            _service = service;
            _dictService = dictService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Langs = new SelectList(await _dictService.GetLangsListAsync((byte)EnumLanguage.Russian), "Id", "Name");
            ViewBag.TranslationLangs = new SelectList(await _dictService.GetLangsListAsync((byte)EnumLanguage.English), "Id", "Name");
            ViewBag.Types = new SelectList(await _dictService.GetTypesListAsync(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoadData()
        {
            var dataTableDict = Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
            var draw = dataTableDict["draw"];

            TranslatorWordFilterDTO filterDTO = new TranslatorWordFilterDTO();
            filterDTO.SortColumn = dataTableDict["columns[" + dataTableDict["order[0][column]"] + "][name]"];
            filterDTO.SortColumnDir = dataTableDict["order[0][dir]"].Contains("asc");
            filterDTO.WordText = dataTableDict["columns[0][search][value]"];
            filterDTO.WordType = !string.IsNullOrEmpty(dataTableDict["columns[2][search][value]"]) ? Convert.ToByte(dataTableDict["columns[2][search][value]"]) : (byte)0;
            filterDTO.PageSize = !string.IsNullOrEmpty(dataTableDict["length"]) ? Convert.ToInt32(dataTableDict["length"]) : 0;
            filterDTO.PageIndex = !string.IsNullOrEmpty(dataTableDict["start"]) ? Convert.ToInt32(dataTableDict["start"]) : 0;

            var result = await _service.GetWordsDataForTable(filterDTO);
            return Json(new { draw, recordsFiltered = result.Item2, recordsTotal = result.Item2, data = result.Item1 });
        }

        [HttpPost]
        public async Task<IActionResult> Create(WordTranslationCreateViewModel model)
        {
            var dto = _mapper.Map<TranslationWordInsertDTO>(model);
            var result = await _service.InsertTranslationWordAsync(dto);
            if (result.IsSuccess)
                return Ok(result);
            else
                return BadRequest(result);
        }

        public async Task<IActionResult> Details(int wordId) => Ok(await _service.GetDetailsTranslationWordAsync(wordId));

        [HttpPost]
        public async Task<IActionResult> Edit(WordTranslationEditViewModel model)
        {
            var dto = _mapper.Map<TranslationWordUpdateDTO>(model);
            var result = await _service.UpdateTranslationWordAsync(dto);
            if (result.IsSuccess)
                return Ok(result);
            else
                return BadRequest(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int deleteWordId) => Ok(await _service.DeleteTranslationWordAsync(deleteWordId));
    }
}

TranslatorProject.WebUI/Views/Shared/_Layout.cshtml
@using TranslatorProject.Common.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TranslatorV1.0</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TranslatorV1.0</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Translator" asp-action="Index">Переводчик</a>
                            </li>
                        }
                        @if (User.IsInRole(GlobalConstants.Roles.Administrator))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Пользователи</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="WordTranslation" asp-action="Index">Справочник слов</a>
                            </li>
                        }
                    </ul>
                </div>

                @if (User.Identity.IsAuthenticated)
                {
                    <form class="form-inline my-2 my-lg-0" asp-controller="Account" asp-action="LogOff" asp-route-returnUrl="@(this.Url.Action("Index", "Home"))">
                        <button type="submit" class="nav-link btn btn-link text-dark">Выйти</button>
                    </form>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="alert-container">
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Переводчик TranslatorV1.0
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validate/localization/messages_ru.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>

    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>